// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsMuWuwOzsoJsQV6FJnM0_Actay76CWuY',
    appId: '1:464291497880:web:6c9915a3342acf48d24ded',
    messagingSenderId: '464291497880',
    projectId: 'mobcar-d0756',
    authDomain: 'mobcar-d0756.firebaseapp.com',
    storageBucket: 'mobcar-d0756.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2PGdphBnaeBPNNKO3FQ7DPxwwZ42FH6Q',
    appId: '1:464291497880:android:debd2ab9bf1b4eb7d24ded',
    messagingSenderId: '464291497880',
    projectId: 'mobcar-d0756',
    storageBucket: 'mobcar-d0756.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChUFfFP9vz1Rccqgj75W_HcVi3Sow6F80',
    appId: '1:464291497880:ios:7bd7d6a9555842e2d24ded',
    messagingSenderId: '464291497880',
    projectId: 'mobcar-d0756',
    storageBucket: 'mobcar-d0756.appspot.com',
    iosClientId: '464291497880-r9ojl0asa4kftc7160noskmgr2kics00.apps.googleusercontent.com',
    iosBundleId: 'com.mobcar.mobcar',
  );
}
